name: MYSELF API CI

on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths:
      - '**'
      - '!.commit_template'
      - '!.eslintignore'
      - '!.eslintrc'
      - '!.gitignore'
      - '!.node-version'
      - '!.prettierrc.js'
      - '!README.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install npm packages
        run: |
          npm install

      - name: Lint and Format
        run: |
          npm run lint & npm run lint:fix

      - name: Create .env
        run: |
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "MONGO_DBNAME=${{ secrets.MONGO_DBNAME }}" >> .env
          echo "TEST_USER_ID=${{ secrets.TEST_USER_ID }}" >> .env
          echo "TEST_USER_NAME=${{ secrets.TEST_USER_NAME }}" >> .env
          echo "TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }}" >> .env
          cat .env

      - name: Test
        run: |
          npm run test
          rm .env

      - name: Deploy to HEROKU
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
